version: "3.3"
services:
  revers-proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
  # express-api:
  #   build: ./express-api
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./express-api:/usr/src/app
  #   tty: true
  #   ports:
  #     - "9001:3001"
  golang-api:
    build: ./golang-api
    environment:
      - "GOPATH=/go"
    volumes:
      - ./golang-api/src:/go/src
    command: sh -c "go mod download && go run main.go"
    tty: true
    ports:
      - "8081:8081"
  ui:
    build: ./ui
    environment:
      - NODE_ENV=development
    volumes:
      - ./ui:/usr/src/app
    command: sh -c "yarn start"
    tty: true
    ports:
      - "3080:3000"
  mysql:
    build: ./db/ #Dockerfileからビルドすることを示す
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d #初期データをマウントする場所
    image: sample_db # イメージの名前
    volumes: 
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=sample_db
      - MYSQL_ROOT_PASSWORD=root #コンテナ内のMySQLを起動する際のパスワードを設定